name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust to your primary branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up FTP
        uses: laurengibbonz/lauren_2024
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Specify the local directory to upload
          server-dir: /laurengibbons.com/public_html  # Server directory